---
title: "컴파일러 오류 CS0155"
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-csharp
ms.topic: article
f1_keywords:
- CS0155
helpviewer_keywords:
- CS0155
ms.assetid: 6c92984a-2b10-453e-9cb7-e6a1d1b98aa6
caps.latest.revision: 
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: 6923b9e493518506e69791056edf2f9ecb39841e
ms.sourcegitcommit: 83dd5ec003e788ccb3e33f3412a7af39ae347646
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/15/2018
---
# <a name="compiler-error-cs0155"></a>컴파일러 오류 CS0155
Catch 또는 Throw된 형식은 System.Exception에서 파생되어야 합니다.  
  
 **System.Exception** 에서 파생되지 않는 데이터 형식을 [catch](../../csharp/language-reference/keywords/try-catch.md) 블록에 전달하려고 했습니다. **System.Exception** 에서 파생된 데이터 형식만 **catch** 블록에 전달할 수 있습니다. 자세한 내용은 참조 [예외 처리문](../../csharp/language-reference/keywords/exception-handling-statements.md) 및 [예외 및 예외 처리](../../csharp/programming-guide/exceptions/index.md)합니다.  
  
 다음 샘플에서는 CS0155를 생성합니다.  
  
```csharp  
// CS0155.cs  
using System;  
  
namespace MyNamespace  
{  
    public class MyClass2  
    // try the following line instead  
    // public class MyClass2 : Exception  
    {  
    }  
    public class MyClass  
    {  
        public static void Main()  
        {  
            try  
            {  
            }  
            catch (MyClass2)   // CS0155, resolves if you derive MyClass2 from Exception  
            {  
            }  
        }  
    }  
}  
```
