---
title: "컴파일러 오류 CS1631"
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-csharp
ms.topic: article
f1_keywords:
- CS1631
helpviewer_keywords:
- CS1631
ms.assetid: bf0c5ff9-90a3-4db6-b4ee-0b93e31614e0
caps.latest.revision: 
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: 6043f4c45179c42fc012b0ed3f32738c5620f73b
ms.sourcegitcommit: 83dd5ec003e788ccb3e33f3412a7af39ae347646
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/15/2018
---
# <a name="compiler-error-cs1631"></a>컴파일러 오류 CS1631
catch 절 본문에서는 값을 생성할 수 없습니다.  
  
 yield 문은 catch 절의 본문 내에서 허용되지 않습니다. 이 오류를 방지하려면 yield 문을 catch 절 본문 밖으로 이동합니다.  
  
 다음 샘플에서는 CS1631을 생성합니다.  
  
```csharp  
// CS1631.cs  
using System;  
using System.Collections;  
  
public class C : IEnumerable  
{  
   public IEnumerator GetEnumerator()   
   {  
      try  
      {  
      }  
      catch(Exception e)  
      {  
        yield return this;  // CS1631  
      }  
   }    
  
   public static void Main()   
   {  
   }  
}  
```
